<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Qxf2                Services_stripe__2e55a3</name>
   <tag></tag>
   <elementGuidId>0a77c112-ea5c-4974-aba0-53a69ac0969e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='stripe_checkout_app']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;stripe_checkout_app&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>13273067-cb44-474a-9179-2a1c80dde853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d42ed3a3-b515-4d7f-9195-3855fe19f507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=408b9dff-80a6-99a5-d781-8ae493a34596</value>
      <webElementGuid>70d0ea75-5cf3-43d6-b537-8b75a02c794f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>0c1d1f8c-49ba-4a90-8ed0-2960f22ca9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>60280d88-d877-4248-a1a0-033271644813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>815fd1c9-a205-4357-8dca-dffe51cdc32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iframe[@class=&quot;stripe_checkout_app&quot;]</value>
      <webElementGuid>3b730e5b-f695-465d-a9e3-9a2d0b024d31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='stripe_checkout_app']</value>
      <webElementGuid>4a7bb9f3-5ac2-499b-b512-764a2860baff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1b9756b7-f301-4104-8150-0c20dca92eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=408b9dff-80a6-99a5-d781-8ae493a34596' and @name = 'stripe_checkout_app']</value>
      <webElementGuid>e618b921-0825-4148-bb22-5d469b9f5149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
