<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payer 353,00INR_cc-exp</name>
   <tag></tag>
   <elementGuidId>52d0fe76-2b8e-442a-ad33-7336b5868541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cc-exp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc-exp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7400585e-018c-489d-8e5d-4aec68534570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>db6f9428-904b-45d9-967e-ce9e29a5c7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control focus</value>
      <webElementGuid>5905a986-5222-4f3c-9b4b-f62cb7ba154b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>177beea3-1ea5-4dc7-8dcf-a6d4cddc6a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a61e4539-548b-4916-951a-f15c33929004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d5268498-4915-4e0d-9c06-159916594c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>36e81d43-7d8c-4ea7-ab22-b69f894d4485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9339bf8-42ef-4292-9d59-f549cabaecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>52213e12-9b81-47d3-8003-8c7e42076a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / AA</value>
      <webElementGuid>335e5c85-1bc1-48c3-ba54-bd0be15569c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-autocompletetype</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8fd862f4-e638-45d7-93b3-d81274d9c586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocompletetype</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f9ece89d-df54-420b-8b43-82ef4063ce11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc-exp&quot;)</value>
      <webElementGuid>8a919308-d2be-4016-87bd-15dbc8cfdb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Cart Items/iframe_Qxf2                Services_stripe__2e55a3</value>
      <webElementGuid>60977dca-48df-43cd-bbcc-e5130d38dc47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cc-exp']</value>
      <webElementGuid>817a23b0-ab0e-4423-8ba7-1a06a95b9b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payer 353,00 INR ₹'])[1]/following::input[3]</value>
      <webElementGuid>2c51f79a-6eeb-4308-a844-53e6df4bbf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example charge'])[1]/following::input[3]</value>
      <webElementGuid>c1b3ad43-2342-4aad-8f47-0f66034c826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0e94c49a-0282-4220-9d37-0a0db16e6358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cc-exp' and @type = 'tel' and @placeholder = 'MM / AA']</value>
      <webElementGuid>7dba5e2b-1087-4ce9-b983-2ee7d44395f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
