<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Total Rupees 353</name>
   <tag></tag>
   <elementGuidId>afc959f6-7751-474c-b12a-a757da5fa152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='total']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6c271d5f-cc71-4b10-971c-58b105f77b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justify-content-center h4 top-space-20</value>
      <webElementGuid>fa3876dd-74b1-44f6-9d34-66c9c0aceabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>c08a6fe0-ac3f-4bb9-92b0-9345c85fd05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total: Rupees 353</value>
      <webElementGuid>ba68deb8-bb9b-4b40-9a78-b1bd68da2fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total&quot;)</value>
      <webElementGuid>c306e5c4-501d-4521-87d1-b5c910772e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='total']</value>
      <webElementGuid>bb269346-b4c7-445a-9ce0-a553fdb1870f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mikhail Almond and Talc'])[1]/following::p[1]</value>
      <webElementGuid>0c741f93-e2d5-4234-8981-02c385bbcb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::p[1]</value>
      <webElementGuid>04c4b996-9dc0-4d24-a49e-ebdf22dfaf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay with Card'])[1]/preceding::p[1]</value>
      <webElementGuid>a965c142-6bf4-48ac-b0a4-ab1f1b6b0af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total: Rupees 353']/parent::*</value>
      <webElementGuid>37db9135-4238-4160-a11b-86964696e589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ec0e6d8e-ef18-4a23-b71e-3019f7b1c2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'total' and (text() = 'Total: Rupees 353' or . = 'Total: Rupees 353')]</value>
      <webElementGuid>7bd27529-3939-49ea-90b8-1c278c2b57f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
