<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Temperature</name>
   <tag></tag>
   <elementGuidId>43d1554a-a034-4d57-aed4-bff0730d56c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='temperature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#temperature</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f75a3765-8bfe-4bbc-aa34-94005bbc2867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>temperature</value>
      <webElementGuid>597a25b4-e8c0-4a6b-9387-32863e5d2c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35 °C</value>
      <webElementGuid>2d42cd63-8e0b-4ec0-8202-96468df3041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperature&quot;)</value>
      <webElementGuid>00b4f267-806c-4a35-b055-414b1c2f6fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='temperature']</value>
      <webElementGuid>71fd2a60-fac4-4b47-9d0a-4614a28dcc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='weather']/span</value>
      <webElementGuid>0ccc1fc7-bf8b-48a2-a538-4c3fb819a12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current temperature'])[1]/following::span[2]</value>
      <webElementGuid>1192808e-f4ee-493f-90ec-9b42c344c6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moisturizers'])[1]/preceding::span[1]</value>
      <webElementGuid>b34f8cc7-d603-4efb-ba40-3e4af4cc1f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>1fbfdccb-31bd-4a15-b0d0-1116fc14f40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'temperature' and (text() = '35 °C' or . = '35 °C')]</value>
      <webElementGuid>3af4e2a1-b912-47c5-b89d-0c591ffc1326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
